# Generated by Django 4.2.8 on 2025-06-22 09:48
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
