# Generated by Django 5.2.3 on 2025-06-22 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_price_per_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='company_username',
            field=models.ForeignKey(limit_choices_to=models.Q(('field_of_work', 'CUSTOMER'), _negated=True), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
